- name: appsetup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name: nodejs instalisation
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: mongodb setup
  ansible.builtin.import_role:
    name: common
    tasks_from: monogodb-setup

- name: starting services
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd