- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup

- name: python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: system start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd